/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ProductReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'product';
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brandName?: string;
  hero?: {
    eyebrow?: string;
    title?: string;
    description?: string;
    primaryLabel?: string;
    secondaryLabel?: string;
    featuredProduct?: ProductReference;
  };
  metrics?: Array<{
    value?: string;
    label?: string;
    _key: string;
  }>;
  story?: {
    eyebrow?: string;
    title?: string;
    description?: string;
    imageUrl?: string;
    featuredProduct?: ProductReference;
    promises?: Array<string>;
  };
};

export type FragranceCategory = {
  _id: string;
  _type: 'fragranceCategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subtitle?: string;
  imageUrl?: string;
  badge?: string;
  filterType?: 'scentFamily' | 'category' | 'occasion';
  filterValue?: string;
  sortOrder?: number;
  surfaces?: Array<string>;
};

export type ScentFamilyReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'scentFamily';
};

export type OccasionReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'occasion';
};

export type Product = {
  _id: string;
  _type: 'product';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
  price?: number;
  category?: 'Pure Extractions' | 'Private Reserve' | 'Atelier Oils' | 'Discovery Sets';
  imageUrl?: string;
  rating?: number;
  reviewCount?: number;
  inStock?: 'in-stock' | 'out-of-stock';
  scentFamily?: ScentFamilyReference;
  occasion?: OccasionReference;
  options?: Array<string>;
};

export type Occasion = {
  _id: string;
  _type: 'occasion';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
  sortOrder?: number;
};

export type ScentFamily = {
  _id: string;
  _type: 'scentFamily';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
  sortOrder?: number;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | ProductReference
  | SiteSettings
  | FragranceCategory
  | ScentFamilyReference
  | OccasionReference
  | Product
  | Occasion
  | ScentFamily
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../perfumes-app/src/core/sanity/content.queries.groq.ts
// Variable: FRAGRANCE_CATEGORIES_QUERY
// Query: *[_type == "fragranceCategory" && $surface in surfaces] | order(sortOrder asc){  title,  subtitle,  imageUrl,  badge,  filterType,  filterValue}
export type FRAGRANCE_CATEGORIES_QUERY_RESULT = Array<{
  title: string | null;
  subtitle: string | null;
  imageUrl: string | null;
  badge: string | null;
  filterType: 'category' | 'occasion' | 'scentFamily' | null;
  filterValue: string | null;
}>;

// Source: ../perfumes-app/src/core/sanity/content.queries.groq.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{  brandName,  hero{    eyebrow,    title,    description,    primaryLabel,    secondaryLabel,    "featuredProduct": featuredProduct->{      "id": _id,      name,      price,      imageUrl,      description    }  },  metrics[]{value, label},  story{    eyebrow,    title,    description,    imageUrl,    "featuredProduct": featuredProduct->{      "id": _id,      name,      price,      imageUrl,      description    },    promises  }}
export type SITE_SETTINGS_QUERY_RESULT = {
  brandName: string | null;
  hero: {
    eyebrow: string | null;
    title: string | null;
    description: string | null;
    primaryLabel: string | null;
    secondaryLabel: string | null;
    featuredProduct: {
      id: string;
      name: string | null;
      price: number | null;
      imageUrl: string | null;
      description: string | null;
    } | null;
  } | null;
  metrics: Array<{
    value: string | null;
    label: string | null;
  }> | null;
  story: {
    eyebrow: string | null;
    title: string | null;
    description: string | null;
    imageUrl: string | null;
    featuredProduct: {
      id: string;
      name: string | null;
      price: number | null;
      imageUrl: string | null;
      description: string | null;
    } | null;
    promises: Array<string> | null;
  } | null;
} | null;

// Source: ../perfumes-app/src/features/products/services/products.queries.groq.ts
// Variable: PRODUCTS_QUERY
// Query: *[_type == "product"] | order(_createdAt desc){  "id": _id,  name,  description,  price,  category,  imageUrl,  rating,  reviewCount,  "inStock": inStock == "in-stock",  "scentFamily": scentFamily->name,  "occasion": occasion->name,  options}
export type PRODUCTS_QUERY_RESULT = Array<{
  id: string;
  name: string | null;
  description: string | null;
  price: number | null;
  category: 'Atelier Oils' | 'Discovery Sets' | 'Private Reserve' | 'Pure Extractions' | null;
  imageUrl: string | null;
  rating: number | null;
  reviewCount: number | null;
  inStock: false | true;
  scentFamily: string | null;
  occasion: string | null;
  options: Array<string> | null;
}>;

// Source: ../perfumes-app/src/features/products/services/products.queries.groq.ts
// Variable: PRODUCT_QUERY
// Query: *[_type == "product" && _id == $id][0]{  "id": _id,  name,  description,  price,  category,  imageUrl,  rating,  reviewCount,  "inStock": inStock == "in-stock",  "scentFamily": scentFamily->name,  "occasion": occasion->name,  options}
export type PRODUCT_QUERY_RESULT = {
  id: string;
  name: string | null;
  description: string | null;
  price: number | null;
  category: 'Atelier Oils' | 'Discovery Sets' | 'Private Reserve' | 'Pure Extractions' | null;
  imageUrl: string | null;
  rating: number | null;
  reviewCount: number | null;
  inStock: false | true;
  scentFamily: string | null;
  occasion: string | null;
  options: Array<string> | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "fragranceCategory" && $surface in surfaces] | order(sortOrder asc){\n  title,\n  subtitle,\n  imageUrl,\n  badge,\n  filterType,\n  filterValue\n}': FRAGRANCE_CATEGORIES_QUERY_RESULT;
    '*[_type == "siteSettings"][0]{\n  brandName,\n  hero{\n    eyebrow,\n    title,\n    description,\n    primaryLabel,\n    secondaryLabel,\n    "featuredProduct": featuredProduct->{\n      "id": _id,\n      name,\n      price,\n      imageUrl,\n      description\n    }\n  },\n  metrics[]{value, label},\n  story{\n    eyebrow,\n    title,\n    description,\n    imageUrl,\n    "featuredProduct": featuredProduct->{\n      "id": _id,\n      name,\n      price,\n      imageUrl,\n      description\n    },\n    promises\n  }\n}': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "product"] | order(_createdAt desc){\n  "id": _id,\n  name,\n  description,\n  price,\n  category,\n  imageUrl,\n  rating,\n  reviewCount,\n  "inStock": inStock == "in-stock",\n  "scentFamily": scentFamily->name,\n  "occasion": occasion->name,\n  options\n}': PRODUCTS_QUERY_RESULT;
    '*[_type == "product" && _id == $id][0]{\n  "id": _id,\n  name,\n  description,\n  price,\n  category,\n  imageUrl,\n  rating,\n  reviewCount,\n  "inStock": inStock == "in-stock",\n  "scentFamily": scentFamily->name,\n  "occasion": occasion->name,\n  options\n}': PRODUCT_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
  interface SanityQueries extends globalThis.SanityQueries {}
}
